### ISSUE TITLE
Feature: tap/tzx speed loader

### ISSUE THREAD

**Issue by rickard-von-essen** [alvieboy/ZXInterfaceZ#25]
Allow games/software to be loaded (almost) instantly.

**Comment by alvieboy** [comment]
Now, this can be tricky... any good tap/tzx to sna algorithm out there ?

**Comment by rickard-von-essen** [comment]
I don't know, but the _Smartcard v2 for Spectrum_ load `.tap`'s instantly. Have to figure out how.

**Comment by rickard-von-essen** [comment]
http://blog.retroleum.co.uk/smart-card-for-zx-spectrum/

**Comment by alvieboy** [comment]
Standard TAP files are easy, TZX ones and some weird TAP are not. I guess that in theory we could run a virtual z80 inside the ESP32 and convert them on the fly, unsure if we have enough memory though

**Comment by alvieboy** [comment]
Basic TAP quickload support added.
