### ISSUE TITLE
Feature: Kempston joystick interfaces

### ISSUE THREAD

**Issue by rickard-von-essen** [alvieboy/ZXInterfaceZ#26]
Support 2x DSUB 9-pin Kempston  (Port 31) joystick interfaces. It is possible to support 2 fire buttons and to have a small amount
of power available on pins 5 and 7 for joysticks that require it (EG: Megadrive pads).

**Comment by alvieboy** [comment]
Plan is to have a small Kempston2USB adaptor. I already started work on that. We don't have room currently on the board, those connectors do take quite some space.

Example, with a standard USB connector (the big square one).

![image](https://user-images.githubusercontent.com/146481/88948261-9af01800-d289-11ea-97f3-a981bcb9551c.png)

**Comment by alvieboy** [comment]
Prototype USB board ordered. 

![image](https://user-images.githubusercontent.com/146481/101663131-3799a200-3a42-11eb-8a69-fa947fe3967c.png)

**Comment by alvieboy** [comment]
Rev 1 of the board is produced and working.
