### ISSUE TITLE
Report Git version on status page and on serial console

### ISSUE THREAD

**Issue by rickard-von-essen** [alvieboy/ZXInterfaceZ#29]
Report the version determined from `git describe --tags --dirty` on the web UI's _status page_ and on the _serial console_.

**Comment by alvieboy** [comment]
On startup (console):

I (2839) ZX InterfaceZ: InterfaceZ version: v1.0 2020/03/30 TAG_V01-286-g461b41e-dirty
I (2849) ZX InterfaceZ:   built Tue 11 Aug 09:49:20 UTC 2020

**Comment by rickard-von-essen** [comment]
Looks great! It will help a lot when handling bugs in the future.
