### ISSUE TITLE
WIP: Use mDNS to broadcast a name

### ISSUE THREAD

**Issue by rickard-von-essen** [alvieboy/ZXInterfaceZ#36]
Currently not working

**Comment by alvieboy** [comment]
Yes, it's rather unclear why it does not work. I'll have to dig inside the TCP/IP layer.

**Comment by rickard-von-essen** [comment]
I can also have a look at tomorrow. Is this enablade by default or do I have to change anything?

**Comment by alvieboy** [comment]
its enabled and I think properly set up. But MDNS requests seem to not reach the mDNS code. See mdns_* calls in "wifi.c"
