### ISSUE TITLE
Loose microUSB connector 

### ISSUE THREAD

**Issue by alvieboy** [alvieboy/ZXInterfaceZ#46]
The current surface-mount microUSB can easily become loose from the board. Convert it into a through-hole (mixed) part for robustness,

**Comment by rickard-von-essen** [comment]
I have used these https://www.aliexpress.com/item/33010624211.html?spm=a2g0s.9042311.0.0.784c4c4dwSaRp1
Which seems similar to the two micro connectors.

**Comment by alvieboy** [comment]
They all look similar, but they have small, important, differences. I'll have to choose one in the upcoming days.
The second problem with those sockets is that they require plated slots, which are not a standard PCB feature, and are easy to miss by the manufacturer.

**Comment by alvieboy** [comment]
Working well on r2.4.
