### ISSUE TITLE
esp32/host/FreeRTOS and esp32/host/freertos clashes on case insensitive filesystem (macOS)

### ISSUE THREAD

**Issue by rickard-von-essen** [alvieboy/ZXInterfaceZ#59]
If you case insensitive filesystem (macOS, Windows 10) you get problems checking out this repo. Maybe we can rename the link `freertos` a bit.

**Comment by alvieboy** [comment]
Yeah, let me try to fix that.

**Comment by alvieboy** [comment]
Care to check if https://github.com/alvieboy/ZXInterfaceZ/commit/522a470d2575fe94059bcf7ae336bc0d4c23d538 fixed it?

**Comment by rickard-von-essen** [comment]
Looks good 👍
