### ISSUE TITLE
LineBuffer.h and linebuffer.h conflict on case insensitive filesystems. 

### ISSUE THREAD

**Issue by nihirash** [alvieboy/ZXInterfaceZ#6]
My usual linux laptop just dead so I've cloned repo from macOS - there was collision between both files(same issue will get all windows users and some linux users). 

I've solved it by creating case sensitive volume but not everyone will make it(btw, some linux users using case insensitive mode of ext4 file system).

I recommend rename LineBuffer.h to LineBuffer.hpp that will solve this issue at all.

**Comment by alvieboy** [comment]
The "C" files are not used on the demo project, so they will be removed.
